name: Auto Assign PR

on:
  pull_request:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Add wladimiiir as reviewer
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          addReviewers: true
          reviewers:
            - wladimiiir

